### ISSUE TITLE
Keyframes ?

### ISSUE THREAD

**Issue by krys-spectralpixel** [DeKugelschieber/BurningByte#14]
Hi,

In this video you show a keyframes system, but I can't find it in the source code ?µ

https://www.youtube.com/watch?v=ZiApW9lYFwg

Thanks

**Comment by DeKugelschieber** [comment]
You can find the 2D animation below src/bb/graphics/animation. Are you looking for the 3D version? That one is not present in the "new" version, but the technique is pretty simple.

You create 2 meshs, one in the first state, one in the second. Pass both to the shader and an interpolation float. Calculate the distance between, like shown in the video.

**Comment by DeKugelschieber** [comment]
Well I found it here: https://github.com/DeKugelschieber/experiments/tree/master/projects/BurningByte-master/old_src/BurningByte/render/animation
But notice this is really really old code.

**Comment by krys-spectralpixel** [comment]
Thanks a lot ;-)
